<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-6084CDG" failures="1" tests="5" name="Default test(failed)" time="11.545" errors="0" timestamp="2024-10-03T20:29:23 CDT">
  <testcase classname="tests.JuiceShopTestsWithTestNG" name="testLogin" time="4.939"/>
  <testcase classname="tests.JuiceShopTestsWithTestNG" name="testAddToCart" time="1.525">
    <failure type="java.lang.AssertionError" message="expected [3] but found [9]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [9]
at tests.JuiceShopTestsWithTestNG.testAddToCart(JuiceShopTestsWithTestNG.java:109)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testAddToCart -->
  <testcase classname="tests.JuiceShopTestsWithTestNG" name="testIncreaseAllQty" time="0.0">
    <skipped/>
  </testcase> <!-- testIncreaseAllQty -->
  <testcase classname="tests.JuiceShopTestsWithTestNG" name="testProductCheckout" time="0.0">
    <skipped/>
  </testcase> <!-- testProductCheckout -->
  <testcase classname="tests.JuiceShopTestsWithTestNG" name="testAddNewAddress" time="0.0">
    <skipped/>
  </testcase> <!-- testAddNewAddress -->
  <testcase classname="tests.JuiceShopTestsWithTestNG" name="testRegisterUser" time="0.0">
    <ignored/>
  </testcase> <!-- testRegisterUser -->
</testsuite> <!-- Default test(failed) -->
